version: '3.1'
services:
  iqfeed:
    image: jaikumarm/iqfeed:v5270
    ports:
     - "5009:5010"
     - "5901:5901"     
     - "9100:9101"
     - "9300:9301"
    environment:
      IQFEED_PRODUCT_ID: "CHANGEME"
      IQFEED_LOGIN: "CHANGEME"
      IQFEED_PASSWORD: "CHANGEME"
